/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage;
import ox.xtext.projectionalEditor.editorLanguage.HtmlAnnotation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Html Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HtmlAnnotationImpl extends MinimalEObjectImpl.Container implements HtmlAnnotation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HtmlAnnotationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EditorLanguagePackage.Literals.HTML_ANNOTATION;
  }

} //HtmlAnnotationImpl
