/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage;
import ox.xtext.projectionalEditor.editorLanguage.JsExtraTag;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Js Extra Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class JsExtraTagImpl extends MinimalEObjectImpl.Container implements JsExtraTag
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JsExtraTagImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EditorLanguagePackage.Literals.JS_EXTRA_TAG;
  }

} //JsExtraTagImpl
