/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Controller</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.AttributeController#getGetter <em>Getter</em>}</li>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.AttributeController#getSetter <em>Setter</em>}</li>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.AttributeController#getValidater <em>Validater</em>}</li>
 * </ul>
 *
 * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getAttributeController()
 * @model
 * @generated
 */
public interface AttributeController extends EObject
{
  /**
   * Returns the value of the '<em><b>Getter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Getter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Getter</em>' containment reference.
   * @see #setGetter(JsSnippet)
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getAttributeController_Getter()
   * @model containment="true"
   * @generated
   */
  JsSnippet getGetter();

  /**
   * Sets the value of the '{@link ox.xtext.projectionalEditor.editorLanguage.AttributeController#getGetter <em>Getter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Getter</em>' containment reference.
   * @see #getGetter()
   * @generated
   */
  void setGetter(JsSnippet value);

  /**
   * Returns the value of the '<em><b>Setter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Setter</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setter</em>' containment reference.
   * @see #setSetter(JsSnippet)
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getAttributeController_Setter()
   * @model containment="true"
   * @generated
   */
  JsSnippet getSetter();

  /**
   * Sets the value of the '{@link ox.xtext.projectionalEditor.editorLanguage.AttributeController#getSetter <em>Setter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setter</em>' containment reference.
   * @see #getSetter()
   * @generated
   */
  void setSetter(JsSnippet value);

  /**
   * Returns the value of the '<em><b>Validater</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Validater</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Validater</em>' containment reference.
   * @see #setValidater(JsSnippet)
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getAttributeController_Validater()
   * @model containment="true"
   * @generated
   */
  JsSnippet getValidater();

  /**
   * Sets the value of the '{@link ox.xtext.projectionalEditor.editorLanguage.AttributeController#getValidater <em>Validater</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Validater</em>' containment reference.
   * @see #getValidater()
   * @generated
   */
  void setValidater(JsSnippet value);

} // AttributeController
