/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Child Id</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.ChildId#getChildId <em>Child Id</em>}</li>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.ChildId#getProjectionId <em>Projection Id</em>}</li>
 * </ul>
 *
 * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getChildId()
 * @model
 * @generated
 */
public interface ChildId extends HtmlAnnotation
{
  /**
   * Returns the value of the '<em><b>Child Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Child Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Child Id</em>' attribute.
   * @see #setChildId(String)
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getChildId_ChildId()
   * @model
   * @generated
   */
  String getChildId();

  /**
   * Sets the value of the '{@link ox.xtext.projectionalEditor.editorLanguage.ChildId#getChildId <em>Child Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Child Id</em>' attribute.
   * @see #getChildId()
   * @generated
   */
  void setChildId(String value);

  /**
   * Returns the value of the '<em><b>Projection Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projection Id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projection Id</em>' reference.
   * @see #setProjectionId(ProjectionDeclaration)
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getChildId_ProjectionId()
   * @model
   * @generated
   */
  ProjectionDeclaration getProjectionId();

  /**
   * Sets the value of the '{@link ox.xtext.projectionalEditor.editorLanguage.ChildId#getProjectionId <em>Projection Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projection Id</em>' reference.
   * @see #getProjectionId()
   * @generated
   */
  void setProjectionId(ProjectionDeclaration value);

} // ChildId
