/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Html Snippet</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.HtmlSnippet#getHtml <em>Html</em>}</li>
 * </ul>
 *
 * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getHtmlSnippet()
 * @model
 * @generated
 */
public interface HtmlSnippet extends EObject
{
  /**
   * Returns the value of the '<em><b>Html</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Html</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Html</em>' containment reference list.
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getHtmlSnippet_Html()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getHtml();

} // HtmlSnippet
