/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Js Extra Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getJsExtraTag()
 * @model
 * @generated
 */
public interface JsExtraTag extends EObject
{
} // JsExtraTag
