/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.editorLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.NodeDeclaration#getNodeName <em>Node Name</em>}</li>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.NodeDeclaration#getProjections <em>Projections</em>}</li>
 *   <li>{@link ox.xtext.projectionalEditor.editorLanguage.NodeDeclaration#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getNodeDeclaration()
 * @model
 * @generated
 */
public interface NodeDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Name</em>' attribute.
   * @see #setNodeName(String)
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getNodeDeclaration_NodeName()
   * @model
   * @generated
   */
  String getNodeName();

  /**
   * Sets the value of the '{@link ox.xtext.projectionalEditor.editorLanguage.NodeDeclaration#getNodeName <em>Node Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Name</em>' attribute.
   * @see #getNodeName()
   * @generated
   */
  void setNodeName(String value);

  /**
   * Returns the value of the '<em><b>Projections</b></em>' containment reference list.
   * The list contents are of type {@link ox.xtext.projectionalEditor.editorLanguage.ProjectionDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Projections</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projections</em>' containment reference list.
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getNodeDeclaration_Projections()
   * @model containment="true"
   * @generated
   */
  EList<ProjectionDeclaration> getProjections();

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link ox.xtext.projectionalEditor.editorLanguage.ComponentDeclaration}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see ox.xtext.projectionalEditor.editorLanguage.EditorLanguagePackage#getNodeDeclaration_Components()
   * @model containment="true"
   * @generated
   */
  EList<ComponentDeclaration> getComponents();

} // NodeDeclaration
