/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.peweb.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.peweb.parser.antlr.internal.InternalEditorLanguageParser;
import org.eclipse.xtext.peweb.services.EditorLanguageGrammarAccess;

public class EditorLanguageParser extends AbstractAntlrParser {

	@Inject
	private EditorLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEditorLanguageParser createParser(XtextTokenStream stream) {
		return new InternalEditorLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EditorDefinitionFile";
	}

	public EditorLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EditorLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
