/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EditorLanguageRuntimeModule extends AbstractEditorLanguageRuntimeModule {
}
