/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.peweb.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.peweb.editorlanguage.ui.internal.EditorlanguageActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EditorLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EditorlanguageActivator.getInstance().getInjector("org.eclipse.xtext.peweb.EditorLanguage");
	}

}
