/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.ide


/**
 * Use this class to register ide components.
 */
class EditorLanguageIdeModule extends AbstractEditorLanguageIdeModule {
}
