/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.peweb.editorLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Id</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId#getComponentType <em>Component Type</em>}</li>
 *   <li>{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId#getAttributeName <em>Attribute Name</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.peweb.editorLanguage.EditorLanguagePackage#getComponentId()
 * @model
 * @generated
 */
public interface ComponentId extends HtmlAnnotation
{
  /**
   * Returns the value of the '<em><b>Component Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Type</em>' reference.
   * @see #setComponentType(ComponentDeclaration)
   * @see org.eclipse.xtext.peweb.editorLanguage.EditorLanguagePackage#getComponentId_ComponentType()
   * @model
   * @generated
   */
  ComponentDeclaration getComponentType();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId#getComponentType <em>Component Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Type</em>' reference.
   * @see #getComponentType()
   * @generated
   */
  void setComponentType(ComponentDeclaration value);

  /**
   * Returns the value of the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attribute Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Name</em>' attribute.
   * @see #setAttributeName(String)
   * @see org.eclipse.xtext.peweb.editorLanguage.EditorLanguagePackage#getComponentId_AttributeName()
   * @model
   * @generated
   */
  String getAttributeName();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId#getAttributeName <em>Attribute Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Name</em>' attribute.
   * @see #getAttributeName()
   * @generated
   */
  void setAttributeName(String value);

} // ComponentId
