/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.peweb.editorLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.xtext.peweb.editorLanguage.EditorLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface EditorLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "editorLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.eclipse.org/xtext/peweb/EditorLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "editorLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EditorLanguagePackage eINSTANCE = org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.EditorDefinitionFileImpl <em>Editor Definition File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorDefinitionFileImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getEditorDefinitionFile()
   * @generated
   */
  int EDITOR_DEFINITION_FILE = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDITOR_DEFINITION_FILE__IMPORTS = 0;

  /**
   * The feature id for the '<em><b>Main Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDITOR_DEFINITION_FILE__MAIN_SECTION = 1;

  /**
   * The number of structural features of the '<em>Editor Definition File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDITOR_DEFINITION_FILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ImportSectionImpl <em>Import Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ImportSectionImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getImportSection()
   * @generated
   */
  int IMPORT_SECTION = 1;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_SECTION__IMPORTS = 0;

  /**
   * The number of structural features of the '<em>Import Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_SECTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ImportImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__NAME = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.MainSectionImpl <em>Main Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.MainSectionImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getMainSection()
   * @generated
   */
  int MAIN_SECTION = 3;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_SECTION__NODES = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_SECTION__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Main Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_SECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.NodeDeclarationImpl <em>Node Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.NodeDeclarationImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getNodeDeclaration()
   * @generated
   */
  int NODE_DECLARATION = 4;

  /**
   * The feature id for the '<em><b>Node Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DECLARATION__NODE_NAME = 0;

  /**
   * The feature id for the '<em><b>Projections</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DECLARATION__PROJECTIONS = 1;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DECLARATION__COMPONENTS = 2;

  /**
   * The number of structural features of the '<em>Node Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_DECLARATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ProjectionDeclarationImpl <em>Projection Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ProjectionDeclarationImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getProjectionDeclaration()
   * @generated
   */
  int PROJECTION_DECLARATION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>View</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_DECLARATION__VIEW = 1;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_DECLARATION__ATTRIBUTES = 2;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_DECLARATION__COMPONENTS = 3;

  /**
   * The number of structural features of the '<em>Projection Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECTION_DECLARATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.AttributeDeclarationImpl <em>Attribute Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.AttributeDeclarationImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getAttributeDeclaration()
   * @generated
   */
  int ATTRIBUTE_DECLARATION = 6;

  /**
   * The feature id for the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECLARATION__ATTRIBUTE_NAME = 0;

  /**
   * The feature id for the '<em><b>Controller</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECLARATION__CONTROLLER = 1;

  /**
   * The number of structural features of the '<em>Attribute Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.HtmlAnnotationImpl <em>Html Annotation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.HtmlAnnotationImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getHtmlAnnotation()
   * @generated
   */
  int HTML_ANNOTATION = 14;

  /**
   * The number of structural features of the '<em>Html Annotation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTML_ANNOTATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ComponentIdImpl <em>Component Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ComponentIdImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getComponentId()
   * @generated
   */
  int COMPONENT_ID = 7;

  /**
   * The feature id for the '<em><b>Component Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ID__COMPONENT_TYPE = HTML_ANNOTATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ID__ATTRIBUTE_NAME = HTML_ANNOTATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Component Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_ID_FEATURE_COUNT = HTML_ANNOTATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.AttributeControllerImpl <em>Attribute Controller</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.AttributeControllerImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getAttributeController()
   * @generated
   */
  int ATTRIBUTE_CONTROLLER = 8;

  /**
   * The feature id for the '<em><b>Getter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CONTROLLER__GETTER = 0;

  /**
   * The feature id for the '<em><b>Setter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CONTROLLER__SETTER = 1;

  /**
   * The feature id for the '<em><b>Validator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CONTROLLER__VALIDATOR = 2;

  /**
   * The number of structural features of the '<em>Attribute Controller</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_CONTROLLER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ChildIdImpl <em>Child Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ChildIdImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getChildId()
   * @generated
   */
  int CHILD_ID = 9;

  /**
   * The feature id for the '<em><b>Child Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHILD_ID__CHILD_ID = HTML_ANNOTATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Projection Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHILD_ID__PROJECTION_ID = HTML_ANNOTATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Child Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHILD_ID_FEATURE_COUNT = HTML_ANNOTATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.TagIdImpl <em>Tag Id</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.TagIdImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getTagId()
   * @generated
   */
  int TAG_ID = 10;

  /**
   * The feature id for the '<em><b>Tag Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG_ID__TAG_NAME = HTML_ANNOTATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tag Id</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TAG_ID_FEATURE_COUNT = HTML_ANNOTATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ComponentDeclarationImpl <em>Component Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ComponentDeclarationImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getComponentDeclaration()
   * @generated
   */
  int COMPONENT_DECLARATION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DECLARATION__NAME = 0;

  /**
   * The feature id for the '<em><b>View</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DECLARATION__VIEW = 1;

  /**
   * The feature id for the '<em><b>Control</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DECLARATION__CONTROL = 2;

  /**
   * The number of structural features of the '<em>Component Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_DECLARATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ComponentControllerImpl <em>Component Controller</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.ComponentControllerImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getComponentController()
   * @generated
   */
  int COMPONENT_CONTROLLER = 12;

  /**
   * The feature id for the '<em><b>Getter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONTROLLER__GETTER = 0;

  /**
   * The feature id for the '<em><b>Setter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONTROLLER__SETTER = 1;

  /**
   * The feature id for the '<em><b>Validator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONTROLLER__VALIDATOR = 2;

  /**
   * The number of structural features of the '<em>Component Controller</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONTROLLER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.HtmlSnippetImpl <em>Html Snippet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.HtmlSnippetImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getHtmlSnippet()
   * @generated
   */
  int HTML_SNIPPET = 13;

  /**
   * The feature id for the '<em><b>Html</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTML_SNIPPET__HTML = 0;

  /**
   * The number of structural features of the '<em>Html Snippet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HTML_SNIPPET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralImpl <em>Code Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteral()
   * @generated
   */
  int CODE_LITERAL = 15;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL__VALUE = 0;

  /**
   * The number of structural features of the '<em>Code Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralStartImpl <em>Code Literal Start</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralStartImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteralStart()
   * @generated
   */
  int CODE_LITERAL_START = 16;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_START__VALUE = 0;

  /**
   * The number of structural features of the '<em>Code Literal Start</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_START_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralMidImpl <em>Code Literal Mid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralMidImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteralMid()
   * @generated
   */
  int CODE_LITERAL_MID = 17;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_MID__VALUE = 0;

  /**
   * The number of structural features of the '<em>Code Literal Mid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_MID_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralEndImpl <em>Code Literal End</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralEndImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteralEnd()
   * @generated
   */
  int CODE_LITERAL_END = 18;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_END__VALUE = 0;

  /**
   * The number of structural features of the '<em>Code Literal End</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CODE_LITERAL_END_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.JsSnippetImpl <em>Js Snippet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.JsSnippetImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getJsSnippet()
   * @generated
   */
  int JS_SNIPPET = 19;

  /**
   * The feature id for the '<em><b>Js</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JS_SNIPPET__JS = 0;

  /**
   * The number of structural features of the '<em>Js Snippet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JS_SNIPPET_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.JsExtraTagImpl <em>Js Extra Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.JsExtraTagImpl
   * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getJsExtraTag()
   * @generated
   */
  int JS_EXTRA_TAG = 20;

  /**
   * The number of structural features of the '<em>Js Extra Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int JS_EXTRA_TAG_FEATURE_COUNT = 0;


  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.EditorDefinitionFile <em>Editor Definition File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Editor Definition File</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.EditorDefinitionFile
   * @generated
   */
  EClass getEditorDefinitionFile();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.EditorDefinitionFile#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Imports</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.EditorDefinitionFile#getImports()
   * @see #getEditorDefinitionFile()
   * @generated
   */
  EReference getEditorDefinitionFile_Imports();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.EditorDefinitionFile#getMainSection <em>Main Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main Section</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.EditorDefinitionFile#getMainSection()
   * @see #getEditorDefinitionFile()
   * @generated
   */
  EReference getEditorDefinitionFile_MainSection();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.ImportSection <em>Import Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Section</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ImportSection
   * @generated
   */
  EClass getImportSection();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.ImportSection#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ImportSection#getImports()
   * @see #getImportSection()
   * @generated
   */
  EReference getImportSection_Imports();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.Import#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.Import#getName()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Name();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.MainSection <em>Main Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Section</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.MainSection
   * @generated
   */
  EClass getMainSection();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.MainSection#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Nodes</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.MainSection#getNodes()
   * @see #getMainSection()
   * @generated
   */
  EReference getMainSection_Nodes();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.MainSection#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.MainSection#getComponents()
   * @see #getMainSection()
   * @generated
   */
  EReference getMainSection_Components();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration <em>Node Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node Declaration</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration
   * @generated
   */
  EClass getNodeDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration#getNodeName <em>Node Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Node Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration#getNodeName()
   * @see #getNodeDeclaration()
   * @generated
   */
  EAttribute getNodeDeclaration_NodeName();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration#getProjections <em>Projections</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Projections</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration#getProjections()
   * @see #getNodeDeclaration()
   * @generated
   */
  EReference getNodeDeclaration_Projections();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.NodeDeclaration#getComponents()
   * @see #getNodeDeclaration()
   * @generated
   */
  EReference getNodeDeclaration_Components();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration <em>Projection Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Projection Declaration</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration
   * @generated
   */
  EClass getProjectionDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getName()
   * @see #getProjectionDeclaration()
   * @generated
   */
  EAttribute getProjectionDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getView <em>View</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>View</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getView()
   * @see #getProjectionDeclaration()
   * @generated
   */
  EReference getProjectionDeclaration_View();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getAttributes()
   * @see #getProjectionDeclaration()
   * @generated
   */
  EReference getProjectionDeclaration_Attributes();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ProjectionDeclaration#getComponents()
   * @see #getProjectionDeclaration()
   * @generated
   */
  EReference getProjectionDeclaration_Components();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeDeclaration <em>Attribute Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Declaration</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeDeclaration
   * @generated
   */
  EClass getAttributeDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeDeclaration#getAttributeName <em>Attribute Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeDeclaration#getAttributeName()
   * @see #getAttributeDeclaration()
   * @generated
   */
  EAttribute getAttributeDeclaration_AttributeName();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeDeclaration#getController <em>Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Controller</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeDeclaration#getController()
   * @see #getAttributeDeclaration()
   * @generated
   */
  EReference getAttributeDeclaration_Controller();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId <em>Component Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Id</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentId
   * @generated
   */
  EClass getComponentId();

  /**
   * Returns the meta object for the reference '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId#getComponentType <em>Component Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Component Type</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentId#getComponentType()
   * @see #getComponentId()
   * @generated
   */
  EReference getComponentId_ComponentType();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentId#getAttributeName <em>Attribute Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attribute Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentId#getAttributeName()
   * @see #getComponentId()
   * @generated
   */
  EAttribute getComponentId_AttributeName();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeController <em>Attribute Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute Controller</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeController
   * @generated
   */
  EClass getAttributeController();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeController#getGetter <em>Getter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Getter</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeController#getGetter()
   * @see #getAttributeController()
   * @generated
   */
  EReference getAttributeController_Getter();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeController#getSetter <em>Setter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Setter</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeController#getSetter()
   * @see #getAttributeController()
   * @generated
   */
  EReference getAttributeController_Setter();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.AttributeController#getValidator <em>Validator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Validator</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.AttributeController#getValidator()
   * @see #getAttributeController()
   * @generated
   */
  EReference getAttributeController_Validator();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.ChildId <em>Child Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Child Id</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ChildId
   * @generated
   */
  EClass getChildId();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.ChildId#getChildId <em>Child Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Child Id</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ChildId#getChildId()
   * @see #getChildId()
   * @generated
   */
  EAttribute getChildId_ChildId();

  /**
   * Returns the meta object for the reference '{@link org.eclipse.xtext.peweb.editorLanguage.ChildId#getProjectionId <em>Projection Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Projection Id</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ChildId#getProjectionId()
   * @see #getChildId()
   * @generated
   */
  EReference getChildId_ProjectionId();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.TagId <em>Tag Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tag Id</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.TagId
   * @generated
   */
  EClass getTagId();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.TagId#getTagName <em>Tag Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tag Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.TagId#getTagName()
   * @see #getTagId()
   * @generated
   */
  EAttribute getTagId_TagName();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration <em>Component Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Declaration</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration
   * @generated
   */
  EClass getComponentDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration#getName()
   * @see #getComponentDeclaration()
   * @generated
   */
  EAttribute getComponentDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration#getView <em>View</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>View</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration#getView()
   * @see #getComponentDeclaration()
   * @generated
   */
  EReference getComponentDeclaration_View();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration#getControl <em>Control</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Control</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentDeclaration#getControl()
   * @see #getComponentDeclaration()
   * @generated
   */
  EReference getComponentDeclaration_Control();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentController <em>Component Controller</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Controller</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentController
   * @generated
   */
  EClass getComponentController();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentController#getGetter <em>Getter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Getter</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentController#getGetter()
   * @see #getComponentController()
   * @generated
   */
  EReference getComponentController_Getter();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentController#getSetter <em>Setter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Setter</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentController#getSetter()
   * @see #getComponentController()
   * @generated
   */
  EReference getComponentController_Setter();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.peweb.editorLanguage.ComponentController#getValidator <em>Validator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Validator</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.ComponentController#getValidator()
   * @see #getComponentController()
   * @generated
   */
  EReference getComponentController_Validator();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.HtmlSnippet <em>Html Snippet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Html Snippet</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.HtmlSnippet
   * @generated
   */
  EClass getHtmlSnippet();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.HtmlSnippet#getHtml <em>Html</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Html</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.HtmlSnippet#getHtml()
   * @see #getHtmlSnippet()
   * @generated
   */
  EReference getHtmlSnippet_Html();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.HtmlAnnotation <em>Html Annotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Html Annotation</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.HtmlAnnotation
   * @generated
   */
  EClass getHtmlAnnotation();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteral <em>Code Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Code Literal</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteral
   * @generated
   */
  EClass getCodeLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteral#getValue()
   * @see #getCodeLiteral()
   * @generated
   */
  EAttribute getCodeLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteralStart <em>Code Literal Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Code Literal Start</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteralStart
   * @generated
   */
  EClass getCodeLiteralStart();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteralStart#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteralStart#getValue()
   * @see #getCodeLiteralStart()
   * @generated
   */
  EAttribute getCodeLiteralStart_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteralMid <em>Code Literal Mid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Code Literal Mid</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteralMid
   * @generated
   */
  EClass getCodeLiteralMid();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteralMid#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteralMid#getValue()
   * @see #getCodeLiteralMid()
   * @generated
   */
  EAttribute getCodeLiteralMid_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteralEnd <em>Code Literal End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Code Literal End</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteralEnd
   * @generated
   */
  EClass getCodeLiteralEnd();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.peweb.editorLanguage.CodeLiteralEnd#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.CodeLiteralEnd#getValue()
   * @see #getCodeLiteralEnd()
   * @generated
   */
  EAttribute getCodeLiteralEnd_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.JsSnippet <em>Js Snippet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Js Snippet</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.JsSnippet
   * @generated
   */
  EClass getJsSnippet();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.peweb.editorLanguage.JsSnippet#getJs <em>Js</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Js</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.JsSnippet#getJs()
   * @see #getJsSnippet()
   * @generated
   */
  EReference getJsSnippet_Js();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.peweb.editorLanguage.JsExtraTag <em>Js Extra Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Js Extra Tag</em>'.
   * @see org.eclipse.xtext.peweb.editorLanguage.JsExtraTag
   * @generated
   */
  EClass getJsExtraTag();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EditorLanguageFactory getEditorLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.EditorDefinitionFileImpl <em>Editor Definition File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorDefinitionFileImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getEditorDefinitionFile()
     * @generated
     */
    EClass EDITOR_DEFINITION_FILE = eINSTANCE.getEditorDefinitionFile();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDITOR_DEFINITION_FILE__IMPORTS = eINSTANCE.getEditorDefinitionFile_Imports();

    /**
     * The meta object literal for the '<em><b>Main Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDITOR_DEFINITION_FILE__MAIN_SECTION = eINSTANCE.getEditorDefinitionFile_MainSection();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ImportSectionImpl <em>Import Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ImportSectionImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getImportSection()
     * @generated
     */
    EClass IMPORT_SECTION = eINSTANCE.getImportSection();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_SECTION__IMPORTS = eINSTANCE.getImportSection_Imports();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ImportImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__NAME = eINSTANCE.getImport_Name();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.MainSectionImpl <em>Main Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.MainSectionImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getMainSection()
     * @generated
     */
    EClass MAIN_SECTION = eINSTANCE.getMainSection();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_SECTION__NODES = eINSTANCE.getMainSection_Nodes();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_SECTION__COMPONENTS = eINSTANCE.getMainSection_Components();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.NodeDeclarationImpl <em>Node Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.NodeDeclarationImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getNodeDeclaration()
     * @generated
     */
    EClass NODE_DECLARATION = eINSTANCE.getNodeDeclaration();

    /**
     * The meta object literal for the '<em><b>Node Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_DECLARATION__NODE_NAME = eINSTANCE.getNodeDeclaration_NodeName();

    /**
     * The meta object literal for the '<em><b>Projections</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_DECLARATION__PROJECTIONS = eINSTANCE.getNodeDeclaration_Projections();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE_DECLARATION__COMPONENTS = eINSTANCE.getNodeDeclaration_Components();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ProjectionDeclarationImpl <em>Projection Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ProjectionDeclarationImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getProjectionDeclaration()
     * @generated
     */
    EClass PROJECTION_DECLARATION = eINSTANCE.getProjectionDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECTION_DECLARATION__NAME = eINSTANCE.getProjectionDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>View</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTION_DECLARATION__VIEW = eINSTANCE.getProjectionDeclaration_View();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTION_DECLARATION__ATTRIBUTES = eINSTANCE.getProjectionDeclaration_Attributes();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROJECTION_DECLARATION__COMPONENTS = eINSTANCE.getProjectionDeclaration_Components();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.AttributeDeclarationImpl <em>Attribute Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.AttributeDeclarationImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getAttributeDeclaration()
     * @generated
     */
    EClass ATTRIBUTE_DECLARATION = eINSTANCE.getAttributeDeclaration();

    /**
     * The meta object literal for the '<em><b>Attribute Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE_DECLARATION__ATTRIBUTE_NAME = eINSTANCE.getAttributeDeclaration_AttributeName();

    /**
     * The meta object literal for the '<em><b>Controller</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_DECLARATION__CONTROLLER = eINSTANCE.getAttributeDeclaration_Controller();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ComponentIdImpl <em>Component Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ComponentIdImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getComponentId()
     * @generated
     */
    EClass COMPONENT_ID = eINSTANCE.getComponentId();

    /**
     * The meta object literal for the '<em><b>Component Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_ID__COMPONENT_TYPE = eINSTANCE.getComponentId_ComponentType();

    /**
     * The meta object literal for the '<em><b>Attribute Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_ID__ATTRIBUTE_NAME = eINSTANCE.getComponentId_AttributeName();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.AttributeControllerImpl <em>Attribute Controller</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.AttributeControllerImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getAttributeController()
     * @generated
     */
    EClass ATTRIBUTE_CONTROLLER = eINSTANCE.getAttributeController();

    /**
     * The meta object literal for the '<em><b>Getter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_CONTROLLER__GETTER = eINSTANCE.getAttributeController_Getter();

    /**
     * The meta object literal for the '<em><b>Setter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_CONTROLLER__SETTER = eINSTANCE.getAttributeController_Setter();

    /**
     * The meta object literal for the '<em><b>Validator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE_CONTROLLER__VALIDATOR = eINSTANCE.getAttributeController_Validator();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ChildIdImpl <em>Child Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ChildIdImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getChildId()
     * @generated
     */
    EClass CHILD_ID = eINSTANCE.getChildId();

    /**
     * The meta object literal for the '<em><b>Child Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHILD_ID__CHILD_ID = eINSTANCE.getChildId_ChildId();

    /**
     * The meta object literal for the '<em><b>Projection Id</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHILD_ID__PROJECTION_ID = eINSTANCE.getChildId_ProjectionId();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.TagIdImpl <em>Tag Id</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.TagIdImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getTagId()
     * @generated
     */
    EClass TAG_ID = eINSTANCE.getTagId();

    /**
     * The meta object literal for the '<em><b>Tag Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TAG_ID__TAG_NAME = eINSTANCE.getTagId_TagName();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ComponentDeclarationImpl <em>Component Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ComponentDeclarationImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getComponentDeclaration()
     * @generated
     */
    EClass COMPONENT_DECLARATION = eINSTANCE.getComponentDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_DECLARATION__NAME = eINSTANCE.getComponentDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>View</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DECLARATION__VIEW = eINSTANCE.getComponentDeclaration_View();

    /**
     * The meta object literal for the '<em><b>Control</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_DECLARATION__CONTROL = eINSTANCE.getComponentDeclaration_Control();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.ComponentControllerImpl <em>Component Controller</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.ComponentControllerImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getComponentController()
     * @generated
     */
    EClass COMPONENT_CONTROLLER = eINSTANCE.getComponentController();

    /**
     * The meta object literal for the '<em><b>Getter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONTROLLER__GETTER = eINSTANCE.getComponentController_Getter();

    /**
     * The meta object literal for the '<em><b>Setter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONTROLLER__SETTER = eINSTANCE.getComponentController_Setter();

    /**
     * The meta object literal for the '<em><b>Validator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONTROLLER__VALIDATOR = eINSTANCE.getComponentController_Validator();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.HtmlSnippetImpl <em>Html Snippet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.HtmlSnippetImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getHtmlSnippet()
     * @generated
     */
    EClass HTML_SNIPPET = eINSTANCE.getHtmlSnippet();

    /**
     * The meta object literal for the '<em><b>Html</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HTML_SNIPPET__HTML = eINSTANCE.getHtmlSnippet_Html();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.HtmlAnnotationImpl <em>Html Annotation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.HtmlAnnotationImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getHtmlAnnotation()
     * @generated
     */
    EClass HTML_ANNOTATION = eINSTANCE.getHtmlAnnotation();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralImpl <em>Code Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteral()
     * @generated
     */
    EClass CODE_LITERAL = eINSTANCE.getCodeLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODE_LITERAL__VALUE = eINSTANCE.getCodeLiteral_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralStartImpl <em>Code Literal Start</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralStartImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteralStart()
     * @generated
     */
    EClass CODE_LITERAL_START = eINSTANCE.getCodeLiteralStart();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODE_LITERAL_START__VALUE = eINSTANCE.getCodeLiteralStart_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralMidImpl <em>Code Literal Mid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralMidImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteralMid()
     * @generated
     */
    EClass CODE_LITERAL_MID = eINSTANCE.getCodeLiteralMid();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODE_LITERAL_MID__VALUE = eINSTANCE.getCodeLiteralMid_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralEndImpl <em>Code Literal End</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.CodeLiteralEndImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getCodeLiteralEnd()
     * @generated
     */
    EClass CODE_LITERAL_END = eINSTANCE.getCodeLiteralEnd();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CODE_LITERAL_END__VALUE = eINSTANCE.getCodeLiteralEnd_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.JsSnippetImpl <em>Js Snippet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.JsSnippetImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getJsSnippet()
     * @generated
     */
    EClass JS_SNIPPET = eINSTANCE.getJsSnippet();

    /**
     * The meta object literal for the '<em><b>Js</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference JS_SNIPPET__JS = eINSTANCE.getJsSnippet_Js();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.peweb.editorLanguage.impl.JsExtraTagImpl <em>Js Extra Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.JsExtraTagImpl
     * @see org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguagePackageImpl#getJsExtraTag()
     * @generated
     */
    EClass JS_EXTRA_TAG = eINSTANCE.getJsExtraTag();

  }

} //EditorLanguagePackage
