/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.peweb.editorLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.eclipse.xtext.peweb.editorLanguage.EditorLanguagePackage
 * @generated
 */
public interface EditorLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EditorLanguageFactory eINSTANCE = org.eclipse.xtext.peweb.editorLanguage.impl.EditorLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Editor Definition File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Editor Definition File</em>'.
   * @generated
   */
  EditorDefinitionFile createEditorDefinitionFile();

  /**
   * Returns a new object of class '<em>Import Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import Section</em>'.
   * @generated
   */
  ImportSection createImportSection();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Main Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main Section</em>'.
   * @generated
   */
  MainSection createMainSection();

  /**
   * Returns a new object of class '<em>Node Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Node Declaration</em>'.
   * @generated
   */
  NodeDeclaration createNodeDeclaration();

  /**
   * Returns a new object of class '<em>Projection Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Projection Declaration</em>'.
   * @generated
   */
  ProjectionDeclaration createProjectionDeclaration();

  /**
   * Returns a new object of class '<em>Attribute Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Declaration</em>'.
   * @generated
   */
  AttributeDeclaration createAttributeDeclaration();

  /**
   * Returns a new object of class '<em>Component Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Id</em>'.
   * @generated
   */
  ComponentId createComponentId();

  /**
   * Returns a new object of class '<em>Attribute Controller</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute Controller</em>'.
   * @generated
   */
  AttributeController createAttributeController();

  /**
   * Returns a new object of class '<em>Child Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Child Id</em>'.
   * @generated
   */
  ChildId createChildId();

  /**
   * Returns a new object of class '<em>Tag Id</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tag Id</em>'.
   * @generated
   */
  TagId createTagId();

  /**
   * Returns a new object of class '<em>Component Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Declaration</em>'.
   * @generated
   */
  ComponentDeclaration createComponentDeclaration();

  /**
   * Returns a new object of class '<em>Component Controller</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Controller</em>'.
   * @generated
   */
  ComponentController createComponentController();

  /**
   * Returns a new object of class '<em>Html Snippet</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Html Snippet</em>'.
   * @generated
   */
  HtmlSnippet createHtmlSnippet();

  /**
   * Returns a new object of class '<em>Html Annotation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Html Annotation</em>'.
   * @generated
   */
  HtmlAnnotation createHtmlAnnotation();

  /**
   * Returns a new object of class '<em>Code Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Literal</em>'.
   * @generated
   */
  CodeLiteral createCodeLiteral();

  /**
   * Returns a new object of class '<em>Code Literal Start</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Literal Start</em>'.
   * @generated
   */
  CodeLiteralStart createCodeLiteralStart();

  /**
   * Returns a new object of class '<em>Code Literal Mid</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Literal Mid</em>'.
   * @generated
   */
  CodeLiteralMid createCodeLiteralMid();

  /**
   * Returns a new object of class '<em>Code Literal End</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Code Literal End</em>'.
   * @generated
   */
  CodeLiteralEnd createCodeLiteralEnd();

  /**
   * Returns a new object of class '<em>Js Snippet</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Js Snippet</em>'.
   * @generated
   */
  JsSnippet createJsSnippet();

  /**
   * Returns a new object of class '<em>Js Extra Tag</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Js Extra Tag</em>'.
   * @generated
   */
  JsExtraTag createJsExtraTag();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  EditorLanguagePackage getEditorLanguagePackage();

} //EditorLanguageFactory
