/**
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package org.eclipse.xtext.peweb.editorLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Html Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.eclipse.xtext.peweb.editorLanguage.EditorLanguagePackage#getHtmlAnnotation()
 * @model
 * @generated
 */
public interface HtmlAnnotation extends EObject
{
} // HtmlAnnotation
