/*
 * generated by Xtext 2.14.0-SNAPSHOT
 */
package ox.xtext.projectionalEditor.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.peweb.editorlanguage.ui.internal.EditorlanguageActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EditorLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EditorlanguageActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EditorlanguageActivator activator = EditorlanguageActivator.getInstance();
		return activator != null ? activator.getInjector(EditorlanguageActivator.OX_XTEXT_PROJECTIONALEDITOR_EDITORLANGUAGE) : null;
	}

}
